export const reducerCases = {
    SET_TOKEN : "SET_TOKEN",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_USER: "SET_USER",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYING: "SET_PLAYING",
    SET_SNACKBAR_STATE: "SET_SNACKBAR_STATE",
    SET_LYRICS: "SET_LYRICS",
    SELECTED_LANGUAGE: "SELECTED_LANGUAGE"
}

